_core:
  default_config_hash: N67AkcKPlikWJbwxABv6MSMpGuXe36qWZfH88pEzeqc
langcode: fi
add_page_meta: true
output_terms: true
output_fields: false
remove_from_admin_routes: false
lib_helper: false
entity_meta:
  created: created
  langcode: langcode
  status: status
  uid: uid
  uuid: uuid
  vid: vid
  name: '0'
enable_ia: false
ia_depth: 3
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  activity_area: '0'
  area: '0'
  categories: '0'
  event_type: '0'
  hobby_area: '0'
  hobby_audience: '0'
  hobby_target_audience: '0'
  tags: '0'
  target_audience: '0'
expose_user_details: '*'
expose_user_details_roles:
  authenticated: '0'
  administrator: '0'
  editor: '0'
current_user_meta:
  name: '0'
  mail: '0'
  roles: '0'
  created: '0'
  access: '0'
group: false
expose_user_details_fields: false
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_label: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements:
  - ''
