warden_allow_requests: true
warden_public_allow_ips: '83.136.254.41,2a04:3541:1000:500:d456:61ff:fee3:7d8d'
warden_server_host_path: 'https://warden.wunder.io'
warden_http_username: 'warden'
warden_http_password: 'wunder'
warden_token: 'aCsTnss8YMAPzU6COnaYKFcr7BTiir'
warden_match_contrib: true
warden_match_custom: true
warden_preg_match_custom: '{^modules\/custom\/*}'
warden_preg_match_contrib: '{^modules\/contrib\/*}'
warden_match_core: true
warden_match_library: false
warden_list_libraries: {  }
_core:
  default_config_hash: QHhUT-UT-9iQoulLBggekAsTvHRFvydlQh5lV0Tb9h8
langcode: fi
