name: tapahtumat
recipe: drupal9

config:
  via: nginx
  xdebug: false
  vhosts: ./.lando/drupal8.conf
  composer_version: 1-latest

tooling:
  bower:
    service: node
  gulp:
    service: node
  index:
    description: Sets up elasticsearch indexes
    cmd:
      - appserver: /app/.lando/index.sh
  migrate:
    description: Imports migrate_source_event migration group
    cmd:
      - appserver: /app/.lando/migrate.sh
  node:
    service: node
  npm:
    service: node
  syncdb:
    description: Synchronizes local db with selected environment
    cmd:
      - appserver: /app/.lando/syncdb.sh
  update:
    description: Updates local db & enables dev components
    cmd:
      - appserver: /app/.lando/update.sh
  xdebug-on:
    service: appserver
    description: Enables xdebug for nginx
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disables xdebug for nginx
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
  yarn:
    service: node

services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    run_as_root:
      - /app/.lando/adminer.sh
    portforward: true
  appserver:
    type: php:7.4
    webroot: web
#    build:
#      - composer install
#    run:
#      - /app/.lando/migrate.sh
    overrides:
      environment:
        WKV_SITE_ENV: lando
        DRUSH_OPTIONS_URI: http://tapahtumat.lndo.site
  database:
    type: mariadb:10.3
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    globals:
#      gulp-cli: latest
#      bower: latest
    # build:
    #   - 'cd /app/web/themes/custom/pori_events/dist/kada-elastic-events && npm install'

  elasticsearch:
    type: compose
    meUser: elasticsearch
    ssl: true
    sslExpose: false
    services:
      image: blacktop/elasticsearch:7
      command: /elastic-entrypoint.sh elasticsearch
      ports:
        - "9400:9400"
        - "9500:9500"
      volumes:
        - ./.lando/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    overrides:
      environment:
        JAVA_HOME: /usr/lib/jvm/default-jvm
        ES_JAVA_OPTS: -Xms512m -Xmx512m
  kibana:
    type: compose
    meUser: kibana
    services:
      image: blacktop/kibana:7
      command: /docker-entrypoint.sh kibana
      ports:
        - "5701:5701"
      volumes:
        - ./.lando/kibana.yml:/usr/share/kibana/config/kibana.yml
      depends_on:
        - elasticsearch
proxy:
  adminer:
    - adminer-tapahtumat.lndo.site
  mailhog:
    - mail-tapahtumat.lndo.site
  elasticsearch:
    - elasticsearch-tapahtumat.lndo.site:9400
  kibana:
    - kibana-tapahtumat.lndo.site:5701

eevents:
  post-db-import:
    - appserver: /app/.lando/update.sh
    - appserver: /app/.lando/index.sh

# Lando version.
version: v3.1.4
