<?php

use Drupal\views\ViewExecutable;
use Drupal\Component\Utility\UrlHelper;

/**
 * Implements hook_migrate_process_info_alter().
 *
 * "extract" migration process plugin needs to have "handle_multiple" property
 * set to TRUE in order to function properly. This hook is a soft-patch
 * until https://www.drupal.org/node/2675156 is fixed.
 */
function migrate_source_example_migrate_process_info_alter(&$definitions) {
  foreach ($definitions as $key => &$definition) {
    if ($key == 'extract') {
      $definition['handle_multiples'] = TRUE;
      break;
    }
  }
}


/**
 * Implements hook_views_pre_render().
 *
 * @param \Drupal\views\ViewExecutable $view
 */
function migrate_source_example_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'event_dashboard')) {

    // Validate pre-registration url. Set to null if invalid url
    $result = $view->result;
    foreach ($result as $key => $item) {
      // field_pre_registration_link is Drupal\Core\Field\FieldItemList class
      $preRegLink = $item->_entity->field_pre_registration_link->getString();
      if ($preRegLink != '') {
        if (!UrlHelper::isValid($preRegLink)) {
          $view->result[$key]->_entity->field_pre_registration_link->setValue(NULL);
        }
      }
    }

    $view->element['#attached']['library'][] = 'migrate_source_example/events-dashboard';
  }
}
