---
# Pori-Events site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  aliases:
    - local
    - lando

  drupal_version: d8

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: web/sites/default/files
    - conf/settings.local.php: web/sites/default/settings.local.php

  local_commands:
    new:
      - shell: echo "Use the 'create' command to create a new project and the 'reset' command to join an existing one."

    # Prepare Drupal directories
    build:
      - make

    create:
      - verify: "Type yes to verify you want to create a new installation (Warning - this will delete your database contents in the process!): "
      - make
      - shell: composer drupal-scaffold
      - drush: site-install config_installer
      - drush: cim -y
      - shell: echo "New installation is complete and configuration has been exported. Please commit it."
      - cleanup

    reset:
      - verify: "Type yes to verify you want to reset your local environment (Warning - this will delete your database contents in the process!): "
      - make
      - drush: site-install config_installer
      - cleanup

    # Basic site update functionality
    update:
      - backup:
         ignore:
          - builds
      - make
      - drush: updb -y
      - drush: cim -y
      - drush: entup -y
      - cleanup

# Develop environment:
dev:

  # Allow development modules to be installed.
  allow_composer_dev: true

  # Test environment only symlinks files
  link:
    - /var/www/pori-events.dev.wunder.io/files: web/sites/default/files

  # We can provide local commands or override global ones.
  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - shell: echo "Creating a new installation should only be done in local environments."

    # Basic site update functionality
    build:
      - make
      - shell: chmod +x scripts/event_import.sh

    update:
      - drush: updb -y
      - drush: cim -y
      - drush: entup -y
      - cleanup
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish

# Test environment:
test:

  aliases: stage

  # Test environment only symlinks files
  link:
    - /var/www/pori-events.stage.wunder.io/files: web/sites/default/files

  # We can provide local commands or override global ones.
  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - shell: echo "Resetting installation should only be done in local environment."

    # Prepare Drupal directories
    build:
      - make
      - shell: chmod +x scripts/event_import.sh

    # Run database updates and restart services.
    update:
      - drush: updb -y
      - drush: cim -y
      - drush: entup -y
      - cleanup
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish

# Production environment:
production:

  aliases: prod

  # Prod environment only symlinks files
  link:
    - /var/www/pori-events.prod.wunder.io/files: web/sites/default/files

  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - shell: echo "Resetting installation should only be done in local environment."

    # Prepare Drupal directories
    build:
      - backup:
         ignore:
          - builds
          - web/sites/default/files
      - make
      - shell: chmod +x scripts/event_import.sh

    # Run database updates and restart services.
    update:
      - drush: updb -y
      - drush: cim -y
      - drush: entup -y
      - cleanup
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish

